#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

# Make 3D mesh in slab of cells.
   runApplication blockMesh || { echo "Error running blockMesh"; exit 1; }

   runApplication surfaceFeatureExtract || { echo "Error running surfaceFeatureExtract"; exit 1; }

   runApplication snappyHexMesh -overwrite || { echo "Error running snappyHexMesh"; exit 1; }

# Generate free surface and run the transient case
    cp 0/alpha.water.orig 0/alpha.water || { echo "Error copying alpha.water"; exit 1; }

    runApplication setFields || { echo "Error running setFields"; exit 1; }

    runApplication decomposePar || { echo "Error running decomposePar"; exit 1; }

    runParallel interFoam || { echo "Error running interFoam"; exit 1; }

    runApplication reconstructPar || { echo "Error running reconstructPar"; exit 1; }

#------------------------------------------------------------------------------
